export const categories = {
  animals: ['tiger', 'rabbit', 'turtle', 'elephant', 'tapir', 'rhino', 'otter', 'rat', 'toucan', 'newt', 'termite', 'eagle', 'emu', 'urchin', 'narwhal', 'lemur', 'raccoon', 'nightingale', 'eel', 'lion', 'leopard', 'dog', 'goat', 'gecko', 'owl', 'wolf', 'fox', 'yak', 'koala', 'ant', 'ape', 'bear', 'beaver', 'buffalo', 'camel', 'cat', 'cheetah', 'cobra', 'crow', 'deer', 'dolphin', 'donkey', 'duck', 'falcon', 'ferret', 'frog', 'giraffe', 'gorilla', 'hamster', 'hare', 'hawk', 'horse', 'hyena', 'ibis', 'iguana', 'jackal', 'jaguar', 'jellyfish', 'kangaroo', 'kiwi', 'llama', 'lobster', 'lynx', 'mole', 'monkey', 'moose', 'mouse', 'octopus', 'orca', 'ostrich', 'panda', 'panther', 'parrot', 'penguin', 'pig', 'puma', 'quail', 'seal', 'shark', 'sheep', 'sloth', 'snake', 'squid', 'swan', 'toad', 'turkey', 'vulture', 'walrus', 'whale', 'wombat', 'zebra', 'rhinoceros', 'alligator', 'crocodile', 'chimpanzee', 'chimp', 'baboon', 'bison', 'boar', 'antelope', 'armadillo', 'badger', 'bat', 'bee', 'beetle', 'butterfly', 'caterpillar', 'chameleon', 'chicken', 'chipmunk', 'clam', 'cod', 'coyote', 'crab', 'cricket', 'dragonfly', 'elk', 'flamingo', 'gazelle', 'goose', 'grasshopper', 'hedgehog', 'heron', 'hippo', 'hippopotamus', 'hornet', 'hummingbird', 'jay', 'ladybug', 'lizard', 'louse', 'macaw', 'magpie', 'mammoth', 'manatee', 'mantis', 'marmot', 'meerkat', 'mongoose', 'mosquito', 'moth', 'mule', 'mussel', 'ox', 'oyster', 'peacock', 'pelican', 'pheasant', 'pigeon', 'platypus', 'pony', 'porcupine', 'possum', 'prawn', 'python', 'rooster', 'salamander', 'salmon', 'sardine', 'scorpion', 'seahorse', 'shrew', 'shrimp', 'skunk', 'snail', 'sparrow', 'spider', 'sponge', 'squirrel', 'starfish', 'stingray', 'stork', 'swordfish', 'tarantula', 'termite', 'tortoise', 'trout', 'tuna', 'wasp', 'weasel', 'woodpecker', 'worm', 'wren'],
  food: ['taco', 'omelette', 'enchilada', 'apple', 'egg', 'grape', 'edamame', 'eclair', 'rice', 'empanada', 'avocado', 'orange', 'noodles', 'samosa', 'almond', 'donut', 'toast', 'tomato', 'olive', 'waffle', 'lasagna', 'nachos', 'sushi', 'idli', 'icecream', 'mango', 'okra', 'asparagus', 'salad', 'dumpling', 'garlic', 'carrot', 'ramen', 'nutmeg', 'guava', 'apricot', 'tea', 'espresso', 'onion', 'nectarine', 'hummus', 'sandwich', 'honey', 'yogurt', 'burger', 'raspberry', 'yam', 'melon', 'kiwi', 'jalapeno', 'pasta', 'pizza', 'quinoa', 'brownie', 'burrito', 'coconut', 'croissant', 'curry', 'falafel', 'fig', 'kebab', 'lemon', 'lentil', 'muffin', 'papaya', 'peach', 'pear', 'pickle', 'potato', 'pudding', 'spinach', 'stew', 'vanilla', 'bacon', 'bagel', 'banana', 'barley', 'bean', 'beef', 'beetroot', 'biscuit', 'bread', 'broccoli', 'butter', 'cabbage', 'cake', 'candy', 'cashew', 'cauliflower', 'celery', 'cereal', 'cheese', 'cherry', 'chicken', 'chickpea', 'chili', 'chips', 'chocolate', 'chutney', 'cinnamon', 'clove', 'cookie', 'corn', 'cucumber', 'custard', 'date', 'dosa', 'fish', 'flour', 'fries', 'ginger', 'gnocchi', 'granola', 'gravy', 'ham', 'hazelnut', 'jam', 'jelly', 'ketchup', 'lime', 'lychee', 'macaroni', 'mayonnaise', 'meatball', 'milk', 'mint', 'mushroom', 'mustard', 'naan', 'oatmeal', 'oats', 'omelet', 'oregano', 'pancake', 'paneer', 'paprika', 'parsley', 'pastry', 'pea', 'peanut', 'pepper', 'pineapple', 'plum', 'popcorn', 'pomegranate', 'pork', 'porridge', 'pretzel', 'pumpkin', 'radish', 'ravioli', 'risotto', 'roll', 'saffron', 'sausage', 'scone', 'shrimp', 'soup', 'soy', 'spaghetti', 'steak', 'strawberry', 'sugar', 'syrup', 'tart', 'tofu', 'tortilla', 'turnip', 'walnut', 'watermelon', 'wheat', 'wrap', 'zucchini'],
  countries: ['india', 'argentina', 'australia', 'austria', 'angola', 'albania', 'armenia', 'andorra', 'egypt', 'estonia', 'ecuador', 'eritrea', 'ethiopia', 'england', 'denmark', 'dominica', 'djibouti', 'italy', 'indonesia', 'iran', 'iraq', 'ireland', 'iceland', 'israel', 'laos', 'latvia', 'lebanon', 'libya', 'lithuania', 'luxembourg', 'mexico', 'malaysia', 'maldives', 'malta', 'mali', 'morocco', 'nepal', 'norway', 'nigeria', 'namibia', 'niger', 'oman', 'pakistan', 'panama', 'paraguay', 'peru', 'poland', 'portugal', 'qatar', 'romania', 'russia', 'rwanda', 'spain', 'sweden', 'switzerland', 'serbia', 'singapore', 'somalia', 'sudan', 'thailand', 'tunisia', 'turkey', 'uganda', 'ukraine', 'uruguay', 'vietnam', 'yemen', 'zambia', 'zimbabwe', 'brazil', 'belgium', 'belarus', 'belize', 'bhutan', 'bolivia', 'botswana', 'bulgaria', 'cambodia', 'cameroon', 'canada', 'chad', 'chile', 'china', 'colombia', 'croatia', 'cuba', 'cyprus', 'france', 'finland', 'fiji', 'gabon', 'gambia', 'georgia', 'germany', 'ghana', 'greece', 'guyana', 'haiti', 'hungary', 'japan', 'jamaica', 'jordan', 'kenya', 'kuwait', 'afghanistan', 'algeria', 'azerbaijan', 'bahamas', 'bahrain', 'bangladesh', 'barbados', 'benin', 'brunei', 'burundi', 'comoros', 'congo', 'grenada', 'guatemala', 'guinea', 'honduras', 'kazakhstan', 'kiribati', 'kosovo', 'kyrgyzstan', 'lesotho', 'liberia', 'liechtenstein', 'madagascar', 'malawi', 'mauritania', 'mauritius', 'micronesia', 'moldova', 'monaco', 'mongolia', 'montenegro', 'mozambique', 'myanmar', 'nauru', 'netherlands', 'nicaragua', 'palau', 'philippines', 'samoa', 'senegal', 'seychelles', 'slovakia', 'slovenia', 'suriname', 'syria', 'taiwan', 'tajikistan', 'tanzania', 'togo', 'tonga', 'turkmenistan', 'tuvalu', 'uzbekistan', 'vanuatu', 'venezuela'],
  things: ['table', 'eraser', 'radio', 'oven', 'notebook', 'key', 'yoyo', 'orange', 'envelope', 'engine', 'earphone', 'easel', 'lamp', 'pencil', 'laptop', 'phone', 'earring', 'guitar', 'ring', 'glass', 'spoon', 'needle', 'ruler', 'rope', 'egg', 'globe', 'umbrella', 'anchor', 'robot', 'towel', 'wallet', 'watch', 'chair', 'camera', 'clock', 'candle', 'bottle', 'basket', 'brush', 'book', 'button', 'box', 'backpack', 'mirror', 'magnet', 'mug', 'newspaper', 'pillow', 'plate', 'poster', 'printer', 'scissors', 'shoe', 'soap', 'suitcase', 'ticket', 'toothbrush', 'vase', 'apron', 'axe', 'balloon', 'bag', 'battery', 'bed', 'bell', 'belt', 'bench', 'bicycle', 'blanket', 'boot', 'bowl', 'bracelet', 'bucket', 'calculator', 'calendar', 'cap', 'carpet', 'cart', 'cup', 'curtain', 'cushion', 'desk', 'diary', 'dish', 'door', 'drawer', 'drum', 'fan', 'flag', 'flashlight', 'fork', 'frame', 'fridge', 'funnel', 'hammer', 'handle', 'hanger', 'hat', 'headphone', 'helmet', 'hook', 'jacket', 'jar', 'jug', 'kettle', 'keyboard', 'knife', 'ladder', 'lantern', 'lock', 'map', 'marker', 'mat', 'microphone', 'monitor', 'mop', 'mouse', 'nail', 'napkin', 'necklace', 'net', 'pan', 'paper', 'pen', 'piano', 'pipe', 'plug', 'pot', 'purse', 'quilt', 'racket', 'razor', 'remote', 'ribbon', 'rug', 'saw', 'scarf', 'screw', 'shelf', 'shirt', 'shovel', 'sink', 'skateboard', 'sock', 'sofa', 'speaker', 'stamp', 'stapler', 'stool', 'stove', 'straw', 'string', 'sword', 'syringe', 'telephone', 'television', 'tent', 'thermometer', 'tie', 'toaster', 'toy', 'tray', 'tripod', 'trophy', 'trumpet', 'tweezers', 'vacuum', 'wheel', 'whistle', 'wire', 'wrench', 'zipper'],
} as const;

export type Category = keyof typeof categories;

export function normalizeWord(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z]/g, '');
}

export function isValidWord(category: Category, word: string) {
  return (categories[category] as readonly string[]).includes(normalizeWord(word));
}

export function isWellFormedWord(value: string) {
  return /^[a-z]{2,32}$/i.test(value.trim());
}

export const blockedWords = new Set(['ass', 'arse', 'bastard', 'bitch', 'cunt', 'damn', 'dick', 'fag', 'fuck', 'nigger', 'piss', 'shit', 'slut', 'whore']);

export function isBlockedWord(word: string) {
  return blockedWords.has(normalizeWord(word));
}

export function isValidCategoryWord(category: Category, value: string) {
  return isWellFormedWord(value) && !isBlockedWord(value) && isValidWord(category, value);
}

export function getWords(category: Category, letter: string, used: string[] = []) {
  const usedSet = new Set(used.map(normalizeWord));
  return (categories[category] as readonly string[]).filter((word) => word.startsWith(letter.toLowerCase()) && !usedSet.has(word));
}
